---
- name: Installing dnsmasq
  ansible.builtin.include_role:
    name: andrewrothstein.dnsmasq
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Disabling the systemd-resolved service
  become: '{{ dnsmasq_configure_privilege_escalate }}'
  become_user: root
  when: >-
    dnsmasq_configure_activate
    and dnsmasq_configure_disable_systemd_resolved
    and dnsmasq_configure_should_disable_systemd_resolved
  ansible.builtin.service:
    name: systemd-resolved
    state: stopped
    enabled: false
- name: Templatizing {{ dnsmasq_configure_conf_path }}
  become: '{{ dnsmasq_configure_privilege_escalate }}'
  become_user: root
  notify: dnsmasq_configure_restart
  ansible.builtin.template:
    src: dnsmasq.conf.j2
    dest: '{{ dnsmasq_configure_conf_path }}'
    mode: '644'
- name: Enabling the dnsmasq service
  become: '{{ dnsmasq_configure_privilege_escalate }}'
  become_user: root
  when: dnsmasq_configure_activate
  ansible.builtin.service:
    name: dnsmasq
    state: started
    enabled: true
